import { Doc } from './_generated/dataModel'

export const TEXT_CHUNKS: Doc<'games'>['textElementsCollection'] = [
  [
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w1' },
    { type: 'space', id: 's1' },
    { type: 'word', letters: ['q', 'u', 'i', 'c', 'k'], id: 'w2' },
    { type: 'space', id: 's2' },
    { type: 'word', letters: ['b', 'r', 'o', 'w', 'n'], id: 'w3' },
    { type: 'space', id: 's3' },
    { type: 'word', letters: ['f', 'o', 'x'], id: 'w4' },
    { type: 'space', id: 's4' },
    { type: 'word', letters: ['j', 'u', 'm', 'p', 's'], id: 'w5' },
    { type: 'space', id: 's5' },
    { type: 'word', letters: ['o', 'v', 'e', 'r'], id: 'w6' },
    { type: 'space', id: 's6' },
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w7' },
    { type: 'space', id: 's7' },
    { type: 'word', letters: ['l', 'a', 'z', 'y'], id: 'w8' },
    { type: 'space', id: 's8' },
    { type: 'word', letters: ['d', 'o', 'g'], id: 'w9' },
  ],
  [
    { type: 'word', letters: ['p', 'r', 'o', 'g', 'r', 'a', 'm', 'm', 'i', 'n', 'g'], id: 'w10' },
    { type: 'space', id: 's9' },
    { type: 'word', letters: ['r', 'e', 'q', 'u', 'i', 'r', 'e', 's'], id: 'w11' },
    { type: 'space', id: 's10' },
    { type: 'word', letters: ['p', 'a', 't', 'i', 'e', 'n', 'c', 'e'], id: 'w12' },
    { type: 'space', id: 's11' },
    { type: 'word', letters: ['a', 'n', 'd'], id: 'w13' },
    { type: 'space', id: 's12' },
    { type: 'word', letters: ['c', 'o', 'n', 's', 'i', 's', 't', 'e', 'n', 't'], id: 'w14' },
    { type: 'space', id: 's13' },
    { type: 'word', letters: ['p', 'r', 'a', 'c', 't', 'i', 'c', 'e'], id: 'w15' },
  ],
  [
    { type: 'word', letters: ['s', 'h', 'e'], id: 'w16' },
    { type: 'space', id: 's14' },
    { type: 'word', letters: ['w', 'a', 'l', 'k', 'e', 'd'], id: 'w17' },
    { type: 'space', id: 's15' },
    { type: 'word', letters: ['t', 'h', 'r', 'o', 'u', 'g', 'h'], id: 'w18' },
    { type: 'space', id: 's16' },
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w19' },
    { type: 'space', id: 's17' },
    { type: 'word', letters: ['p', 'a', 'r', 'k'], id: 'w20' },
    { type: 'space', id: 's18' },
    { type: 'word', letters: ['e', 'v', 'e', 'r', 'y'], id: 'w21' },
    { type: 'space', id: 's19' },
    { type: 'word', letters: ['m', 'o', 'r', 'n', 'i', 'n', 'g'], id: 'w22' },
  ],
  [
    { type: 'word', letters: ['t', 'e', 'c', 'h', 'n', 'o', 'l', 'o', 'g', 'y'], id: 'w23' },
    { type: 'space', id: 's20' },
    { type: 'word', letters: ['c', 'o', 'n', 't', 'i', 'n', 'u', 'e', 's'], id: 'w24' },
    { type: 'space', id: 's21' },
    { type: 'word', letters: ['t', 'o'], id: 'w25' },
    { type: 'space', id: 's22' },
    { type: 'word', letters: ['e', 'v', 'o', 'l', 'v', 'e'], id: 'w26' },
    { type: 'space', id: 's23' },
    { type: 'word', letters: ['a', 't'], id: 'w27' },
    { type: 'space', id: 's24' },
    { type: 'word', letters: ['a', 'n'], id: 'w28' },
    { type: 'space', id: 's25' },
    { type: 'word', letters: ['a', 's', 't', 'o', 'n', 'i', 's', 'h', 'i', 'n', 'g'], id: 'w29' },
    { type: 'space', id: 's26' },
    { type: 'word', letters: ['p', 'a', 'c', 'e'], id: 'w30' },
  ],
  [
    { type: 'word', letters: ['c', 'o', 'f', 'f', 'e', 'e'], id: 'w31' },
    { type: 'space', id: 's27' },
    { type: 'word', letters: ['i', 's'], id: 'w32' },
    { type: 'space', id: 's28' },
    { type: 'word', letters: ['m', 'y'], id: 'w33' },
    { type: 'space', id: 's29' },
    { type: 'word', letters: ['f', 'a', 'v', 'o', 'r', 'i', 't', 'e'], id: 'w34' },
    { type: 'space', id: 's30' },
    { type: 'word', letters: ['w', 'a', 'y'], id: 'w35' },
    { type: 'space', id: 's31' },
    { type: 'word', letters: ['t', 'o'], id: 'w36' },
    { type: 'space', id: 's32' },
    { type: 'word', letters: ['s', 't', 'a', 'r', 't'], id: 'w37' },
    { type: 'space', id: 's33' },
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w38' },
    { type: 'space', id: 's34' },
    { type: 'word', letters: ['d', 'a', 'y'], id: 'w39' },
  ],
  [
    { type: 'word', letters: ['e', 'x', 'e', 'r', 'c', 'i', 's', 'e'], id: 'w40' },
    { type: 'space', id: 's35' },
    { type: 'word', letters: ['r', 'e', 'g', 'u', 'l', 'a', 'r', 'l', 'y'], id: 'w41' },
    { type: 'space', id: 's36' },
    { type: 'word', letters: ['t', 'o'], id: 'w42' },
    { type: 'space', id: 's37' },
    { type: 'word', letters: ['m', 'a', 'i', 'n', 't', 'a', 'i', 'n'], id: 'w43' },
    { type: 'space', id: 's38' },
    { type: 'word', letters: ['g', 'o', 'o', 'd'], id: 'w44' },
    { type: 'space', id: 's39' },
    { type: 'word', letters: ['h', 'e', 'a', 'l', 't', 'h'], id: 'w45' },
  ],
  [
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w46' },
    { type: 'space', id: 's40' },
    { type: 'word', letters: ['o', 'c', 'e', 'a', 'n'], id: 'w47' },
    { type: 'space', id: 's41' },
    { type: 'word', letters: ['w', 'a', 'v', 'e', 's'], id: 'w48' },
    { type: 'space', id: 's42' },
    { type: 'word', letters: ['c', 'r', 'a', 's', 'h', 'e', 'd'], id: 'w49' },
    { type: 'space', id: 's43' },
    { type: 'word', letters: ['a', 'g', 'a', 'i', 'n', 's', 't'], id: 'w50' },
    { type: 'space', id: 's44' },
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w51' },
    { type: 'space', id: 's45' },
    { type: 'word', letters: ['r', 'o', 'c', 'k', 'y'], id: 'w52' },
    { type: 'space', id: 's46' },
    { type: 'word', letters: ['s', 'h', 'o', 'r', 'e'], id: 'w53' },
  ],
  [
    { type: 'word', letters: ['i', 'n', 'n', 'o', 'v', 'a', 't', 'i', 'o', 'n'], id: 'w54' },
    { type: 'space', id: 's47' },
    { type: 'word', letters: ['r', 'e', 'q', 'u', 'i', 'r', 'e', 's'], id: 'w55' },
    { type: 'space', id: 's48' },
    { type: 'word', letters: ['c', 'r', 'e', 'a', 't', 'i', 'v', 'i', 't', 'y'], id: 'w56' },
    { type: 'space', id: 's49' },
    { type: 'word', letters: ['a', 'n', 'd'], id: 'w57' },
    { type: 'space', id: 's50' },
    { type: 'word', letters: ['w', 'i', 'l', 'l', 'i', 'n', 'g', 'n', 'e', 's', 's'], id: 'w58' },
    { type: 'space', id: 's51' },
    { type: 'word', letters: ['t', 'o'], id: 'w59' },
    { type: 'space', id: 's52' },
    { type: 'word', letters: ['t', 'a', 'k', 'e'], id: 'w60' },
    { type: 'space', id: 's53' },
    { type: 'word', letters: ['r', 'i', 's', 'k', 's'], id: 'w61' },
  ],
  [
    { type: 'word', letters: ['s', 't', 'u', 'd', 'e', 'n', 't', 's'], id: 'w62' },
    { type: 'space', id: 's54' },
    { type: 'word', letters: ['w', 'e', 'r', 'e'], id: 'w63' },
    { type: 'space', id: 's55' },
    { type: 'word', letters: ['e', 'x', 'c', 'i', 't', 'e', 'd'], id: 'w64' },
    { type: 'space', id: 's56' },
    { type: 'word', letters: ['a', 'b', 'o', 'u', 't'], id: 'w65' },
    { type: 'space', id: 's57' },
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w66' },
    { type: 'space', id: 's58' },
    { type: 'word', letters: ['u', 'p', 'c', 'o', 'm', 'i', 'n', 'g'], id: 'w67' },
    { type: 'space', id: 's59' },
    { type: 'word', letters: ['s', 'c', 'i', 'e', 'n', 'c', 'e'], id: 'w68' },
    { type: 'space', id: 's60' },
    { type: 'word', letters: ['f', 'a', 'i', 'r'], id: 'w69' },
  ],
  [
    { type: 'word', letters: ['p', 'h', 'i', 'l', 'o', 's', 'o', 'p', 'h', 'y'], id: 'w70' },
    { type: 'space', id: 's61' },
    { type: 'word', letters: ['e', 'x', 'p', 'l', 'o', 'r', 'e', 's'], id: 'w71' },
    { type: 'space', id: 's62' },
    { type: 'word', letters: ['f', 'u', 'n', 'd', 'a', 'm', 'e', 'n', 't', 'a', 'l'], id: 'w72' },
    { type: 'space', id: 's63' },
    { type: 'word', letters: ['q', 'u', 'e', 's', 't', 'i', 'o', 'n', 's'], id: 'w73' },
    { type: 'space', id: 's64' },
    { type: 'word', letters: ['a', 'b', 'o', 'u', 't'], id: 'w74' },
    { type: 'space', id: 's65' },
    { type: 'word', letters: ['e', 'x', 'i', 's', 't', 'e', 'n', 'c', 'e'], id: 'w75' },
  ],
  [
    { type: 'word', letters: ['g', 'a', 'r', 'd', 'e', 'n', 'i', 'n', 'g'], id: 'w76' },
    { type: 'space', id: 's66' },
    { type: 'word', letters: ['t', 'e', 'a', 'c', 'h', 'e', 's'], id: 'w77' },
    { type: 'space', id: 's67' },
    { type: 'word', letters: ['u', 's'], id: 'w78' },
    { type: 'space', id: 's68' },
    { type: 'word', letters: ['p', 'a', 't', 'i', 'e', 'n', 'c', 'e'], id: 'w79' },
    { type: 'space', id: 's69' },
    { type: 'word', letters: ['a', 'n', 'd'], id: 'w80' },
    { type: 'space', id: 's70' },
    { type: 'word', letters: ['c', 'o', 'n', 'n', 'e', 'c', 't', 'i', 'o', 'n'], id: 'w81' },
    { type: 'space', id: 's71' },
    { type: 'word', letters: ['w', 'i', 't', 'h'], id: 'w82' },
    { type: 'space', id: 's72' },
    { type: 'word', letters: ['n', 'a', 't', 'u', 'r', 'e'], id: 'w83' },
  ],
  [
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w84' },
    { type: 'space', id: 's73' },
    { type: 'word', letters: ['l', 'i', 'b', 'r', 'a', 'r', 'y'], id: 'w85' },
    { type: 'space', id: 's74' },
    { type: 'word', letters: ['w', 'a', 's'], id: 'w86' },
    { type: 'space', id: 's75' },
    { type: 'word', letters: ['f', 'i', 'l', 'l', 'e', 'd'], id: 'w87' },
    { type: 'space', id: 's76' },
    { type: 'word', letters: ['w', 'i', 't', 'h'], id: 'w88' },
    { type: 'space', id: 's77' },
    { type: 'word', letters: ['c', 'u', 'r', 'i', 'o', 'u', 's'], id: 'w89' },
    { type: 'space', id: 's78' },
    { type: 'word', letters: ['r', 'e', 'a', 'd', 'e', 'r', 's'], id: 'w90' },
  ],
  [
    {
      type: 'word',
      letters: ['e', 'n', 't', 'r', 'e', 'p', 'r', 'e', 'n', 'e', 'u', 'r', 's', 'h', 'i', 'p'],
      id: 'w91',
    },
    { type: 'space', id: 's79' },
    { type: 'word', letters: ['i', 'n', 'v', 'o', 'l', 'v', 'e', 's'], id: 'w92' },
    { type: 'space', id: 's80' },
    { type: 'word', letters: ['i', 'd', 'e', 'n', 't', 'i', 'f', 'y', 'i', 'n', 'g'], id: 'w93' },
    { type: 'space', id: 's81' },
    {
      type: 'word',
      letters: ['o', 'p', 'p', 'o', 'r', 't', 'u', 'n', 'i', 't', 'i', 'e', 's'],
      id: 'w94',
    },
    { type: 'space', id: 's82' },
    { type: 'word', letters: ['a', 'n', 'd'], id: 'w95' },
    { type: 'space', id: 's83' },
    { type: 'word', letters: ['s', 'o', 'l', 'v', 'i', 'n', 'g'], id: 'w96' },
    { type: 'space', id: 's84' },
    { type: 'word', letters: ['p', 'r', 'o', 'b', 'l', 'e', 'm', 's'], id: 'w97' },
  ],
  [
    { type: 'word', letters: ['m', 'u', 's', 'i', 'c'], id: 'w98' },
    { type: 'space', id: 's85' },
    { type: 'word', letters: ['h', 'a', 's'], id: 'w99' },
    { type: 'space', id: 's86' },
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w100' },
    { type: 'space', id: 's87' },
    { type: 'word', letters: ['p', 'o', 'w', 'e', 'r'], id: 'w101' },
    { type: 'space', id: 's88' },
    { type: 'word', letters: ['t', 'o'], id: 'w102' },
    { type: 'space', id: 's89' },
    { type: 'word', letters: ['t', 'r', 'a', 'n', 's', 'c', 'e', 'n', 'd'], id: 'w103' },
    { type: 'space', id: 's90' },
    { type: 'word', letters: ['c', 'u', 'l', 't', 'u', 'r', 'a', 'l'], id: 'w104' },
    { type: 'space', id: 's91' },
    { type: 'word', letters: ['b', 'o', 'u', 'n', 'd', 'a', 'r', 'i', 'e', 's'], id: 'w105' },
  ],
  [
    { type: 'word', letters: ['t', 'r', 'a', 'v', 'e', 'l', 'i', 'n', 'g'], id: 'w106' },
    { type: 'space', id: 's92' },
    { type: 'word', letters: ['o', 'p', 'e', 'n', 's'], id: 'w107' },
    { type: 'space', id: 's93' },
    { type: 'word', letters: ['o', 'u', 'r'], id: 'w108' },
    { type: 'space', id: 's94' },
    { type: 'word', letters: ['m', 'i', 'n', 'd', 's'], id: 'w109' },
    { type: 'space', id: 's95' },
    { type: 'word', letters: ['t', 'o'], id: 'w110' },
    { type: 'space', id: 's96' },
    { type: 'word', letters: ['n', 'e', 'w'], id: 'w111' },
    { type: 'space', id: 's97' },
    {
      type: 'word',
      letters: ['p', 'e', 'r', 's', 'p', 'e', 'c', 't', 'i', 'v', 'e', 's'],
      id: 'w112',
    },
  ],
  [
    { type: 'word', letters: ['a', 'r', 't', 'i', 'f', 'i', 'c', 'i', 'a', 'l'], id: 'w113' },
    { type: 'space', id: 's98' },
    {
      type: 'word',
      letters: ['i', 'n', 't', 'e', 'l', 'l', 'i', 'g', 'e', 'n', 'c', 'e'],
      id: 'w114',
    },
    { type: 'space', id: 's99' },
    { type: 'word', letters: ['i', 's'], id: 'w115' },
    { type: 'space', id: 's100' },
    {
      type: 'word',
      letters: ['r', 'e', 'v', 'o', 'l', 'u', 't', 'i', 'o', 'n', 'i', 'z', 'i', 'n', 'g'],
      id: 'w116',
    },
    { type: 'space', id: 's101' },
    { type: 'word', letters: ['h', 'o', 'w'], id: 'w117' },
    { type: 'space', id: 's102' },
    { type: 'word', letters: ['w', 'e'], id: 'w118' },
    { type: 'space', id: 's103' },
    { type: 'word', letters: ['w', 'o', 'r', 'k'], id: 'w119' },
  ],
  [
    { type: 'word', letters: ['c', 'h', 'i', 'l', 'd', 'r', 'e', 'n'], id: 'w120' },
    { type: 'space', id: 's104' },
    { type: 'word', letters: ['l', 'a', 'u', 'g', 'h', 'e', 'd'], id: 'w121' },
    { type: 'space', id: 's105' },
    { type: 'word', letters: ['j', 'o', 'y', 'f', 'u', 'l', 'l', 'y'], id: 'w122' },
    { type: 'space', id: 's106' },
    { type: 'word', letters: ['i', 'n'], id: 'w123' },
    { type: 'space', id: 's107' },
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w124' },
    { type: 'space', id: 's108' },
    { type: 'word', letters: ['p', 'l', 'a', 'y', 'g', 'r', 'o', 'u', 'n', 'd'], id: 'w125' },
  ],
  [
    {
      type: 'word',
      letters: ['s', 'u', 's', 't', 'a', 'i', 'n', 'a', 'b', 'i', 'l', 'i', 't', 'y'],
      id: 'w126',
    },
    { type: 'space', id: 's109' },
    { type: 'word', letters: ['r', 'e', 'q', 'u', 'i', 'r', 'e', 's'], id: 'w127' },
    { type: 'space', id: 's110' },
    { type: 'word', letters: ['c', 'o', 'l', 'l', 'e', 'c', 't', 'i', 'v', 'e'], id: 'w128' },
    { type: 'space', id: 's111' },
    { type: 'word', letters: ['a', 'c', 't', 'i', 'o', 'n'], id: 'w129' },
    { type: 'space', id: 's112' },
    { type: 'word', letters: ['a', 'n', 'd'], id: 'w130' },
    { type: 'space', id: 's113' },
    { type: 'word', letters: ['c', 'o', 'm', 'm', 'i', 't', 'm', 'e', 'n', 't'], id: 'w131' },
  ],
  [
    { type: 'word', letters: ['b', 'o', 'o', 'k', 's'], id: 'w132' },
    { type: 'space', id: 's114' },
    { type: 'word', letters: ['h', 'a', 'v', 'e'], id: 'w133' },
    { type: 'space', id: 's115' },
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w134' },
    { type: 'space', id: 's116' },
    { type: 'word', letters: ['p', 'o', 'w', 'e', 'r'], id: 'w135' },
    { type: 'space', id: 's117' },
    { type: 'word', letters: ['t', 'o'], id: 'w136' },
    { type: 'space', id: 's118' },
    { type: 'word', letters: ['t', 'r', 'a', 'n', 's', 'p', 'o', 'r', 't'], id: 'w137' },
    { type: 'space', id: 's119' },
    { type: 'word', letters: ['u', 's'], id: 'w138' },
    { type: 'space', id: 's120' },
    { type: 'word', letters: ['a', 'n', 'y', 'w', 'h', 'e', 'r', 'e'], id: 'w139' },
  ],
  [
    { type: 'word', letters: ['s', 'c', 'i', 'e', 'n', 't', 'i', 's', 't', 's'], id: 'w140' },
    { type: 'space', id: 's121' },
    { type: 'word', letters: ['a', 'r', 'e'], id: 'w141' },
    { type: 'space', id: 's122' },
    { type: 'word', letters: ['w', 'o', 'r', 'k', 'i', 'n', 'g'], id: 'w142' },
    { type: 'space', id: 's123' },
    { type: 'word', letters: ['t', 'o'], id: 'w143' },
    { type: 'space', id: 's124' },
    { type: 'word', letters: ['u', 'n', 'd', 'e', 'r', 's', 't', 'a', 'n', 'd'], id: 'w144' },
    { type: 'space', id: 's125' },
    { type: 'word', letters: ['c', 'l', 'i', 'm', 'a', 't', 'e'], id: 'w145' },
    { type: 'space', id: 's126' },
    { type: 'word', letters: ['c', 'h', 'a', 'n', 'g', 'e'], id: 'w146' },
  ],
  [
    { type: 'word', letters: ['c', 'r', 'e', 'a', 't', 'i', 'v', 'i', 't', 'y'], id: 'w147' },
    { type: 'space', id: 's127' },
    { type: 'word', letters: ['f', 'l', 'o', 'u', 'r', 'i', 's', 'h', 'e', 's'], id: 'w148' },
    { type: 'space', id: 's128' },
    { type: 'word', letters: ['w', 'h', 'e', 'n'], id: 'w149' },
    { type: 'space', id: 's129' },
    { type: 'word', letters: ['w', 'e'], id: 'w150' },
    { type: 'space', id: 's130' },
    { type: 'word', letters: ['e', 'm', 'b', 'r', 'a', 'c', 'e'], id: 'w151' },
    { type: 'space', id: 's131' },
    { type: 'word', letters: ['c', 'u', 'r', 'i', 'o', 's', 'i', 't', 'y'], id: 'w152' },
  ],
  [
    { type: 'word', letters: ['e', 'x', 'p', 'l', 'o', 'r', 'i', 'n', 'g'], id: 'w153' },
    { type: 'space', id: 's132' },
    { type: 'word', letters: ['n', 'e', 'w'], id: 'w154' },
    { type: 'space', id: 's133' },
    { type: 'word', letters: ['c', 'i', 't', 'i', 'e', 's'], id: 'w155' },
    { type: 'space', id: 's134' },
    { type: 'word', letters: ['a', 'l', 'w', 'a', 'y', 's'], id: 'w156' },
    { type: 'space', id: 's135' },
    { type: 'word', letters: ['b', 'r', 'i', 'n', 'g', 's'], id: 'w157' },
    { type: 'space', id: 's136' },
    { type: 'word', letters: ['u', 'n', 'e', 'x', 'p', 'e', 'c', 't', 'e', 'd'], id: 'w158' },
    { type: 'space', id: 's137' },
    { type: 'word', letters: ['d', 'i', 's', 'c', 'o', 'v', 'e', 'r', 'i', 'e', 's'], id: 'w159' },
  ],
  [
    { type: 'word', letters: ['m', 'a', 't', 'h', 'e', 'm', 'a', 't', 'i', 'c', 's'], id: 'w160' },
    { type: 'space', id: 's138' },
    { type: 'word', letters: ['i', 's'], id: 'w161' },
    { type: 'space', id: 's139' },
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w162' },
    { type: 'space', id: 's140' },
    { type: 'word', letters: ['l', 'a', 'n', 'g', 'u', 'a', 'g', 'e'], id: 'w163' },
    { type: 'space', id: 's141' },
    { type: 'word', letters: ['o', 'f'], id: 'w164' },
    { type: 'space', id: 's142' },
    { type: 'word', letters: ['t', 'h', 'e'], id: 'w165' },
    { type: 'space', id: 's143' },
    { type: 'word', letters: ['u', 'n', 'i', 'v', 'e', 'r', 's', 'e'], id: 'w166' },
  ],
]
